/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ip;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class frmHost extends javax.swing.JFrame {

    /**
     * Creates new form frmHost
     */
    DefaultListModel x;
    int[] vec1;
    int bits;
    int cant;
    int ult;
    DefaultListModel list;
    public frmHost(DefaultListModel x,int [] vec1,int bits,int cant) {
        this.x=x;
        initComponents();
        subred.setModel(x);
        this.vec1=vec1;
        this.bits=bits;
        this.cant=cant;
        ult=-1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subred = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        host = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        subred.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        subred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subredMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subred);

        host.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hostMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(host);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private int[] getIP(){
        String ip = (String) x.elementAt(subred.getSelectedIndex());
        int p=0;
        String []vip=new String[4];
        vip[0]="";
        vip[1]="";
        vip[2]="";
        vip[3]="";
        for(int i=0;i<ip.length();i++){
            if(ip.charAt(i)=='.'){
            p++;
            }else{
                vip[p]+=ip.charAt(i);
            }
        }
        int [] t=new int[4];
        t[0]=Integer.valueOf(vip[0]);
        t[1]=Integer.valueOf(vip[1]);
        t[2]=Integer.valueOf(vip[2]);
        t[3]=Integer.valueOf(vip[3]);
        return t;
    }
    
    private void subredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subredMouseClicked
        // TODO add your handling code here:
        list=new DefaultListModel();
        int []ipRed=getIP();
        
        String ipFullStrng= ipField.IntToBinaryStrg(ipRed[0])+
                            ipField.IntToBinaryStrg(ipRed[1])+
                            ipField.IntToBinaryStrg(ipRed[2])+
                            ipField.IntToBinaryStrg(ipRed[3]);
        String ipStrg="";
        for (int i=0;i<bits;i++){
            ipStrg+=ipFullStrng.charAt(i);
        }
        
        
        for (int i=1;i<cant+1;i++){
            String sip=Integer.toBinaryString(i);
            for (int j=0;sip.length()<32-bits;j++){
                sip="0"+sip;
            }
            String ipFinal=ipStrg+sip;
            String[] vip=new String[4];
            vip[0]="";
            vip[1]="";
            vip[2]="";
            vip[3]="";
            
            for (int j=0;j<8;j++){
                vip[0]+=ipFinal.charAt(j);
                vip[1]+=ipFinal.charAt(j+8);
                vip[2]+=ipFinal.charAt(j+16);
                vip[3]+=ipFinal.charAt(j+24);
            }
            
            list.addElement(Integer.parseInt(vip[0], 2)+"."+Integer.parseInt(vip[1], 2)+"."+Integer.parseInt(vip[2], 2)+"."+Integer.parseInt(vip[3], 2));         
        }
        host.setModel(list);
        
    }//GEN-LAST:event_subredMouseClicked

    private void hostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostMouseClicked
        // TODO add your handling code here:
        String ip = (String) list.elementAt(host.getSelectedIndex());
        if(ult==host.getSelectedIndex()){
            int p=0;
            String []vip=new String[4];
            vip[0]="";
            vip[1]="";
            vip[2]="";
            vip[3]="";
            for(int i=0;i<ip.length();i++){
                if(ip.charAt(i)=='.'){
                    p++;
                }else{
                    vip[p]+=ip.charAt(i);
                }
            }
            int [] t=new int[4];
            t[0]=Integer.valueOf(vip[0]);
            t[1]=Integer.valueOf(vip[1]);
            t[2]=Integer.valueOf(vip[2]);
            t[3]=Integer.valueOf(vip[3]);
            
            ipField.ip=t.clone();
            maskField.mask=vec1.clone();
            
            FrmInfo obj=new FrmInfo();
            obj.setLocationRelativeTo(this);
            obj.setVisible(true);
        }
        else{
            ult=host.getSelectedIndex();
        }
    }//GEN-LAST:event_hostMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new frmHost().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList host;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList subred;
    // End of variables declaration//GEN-END:variables
}
