/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ip;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe
 */
public class FrmPrin extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrin
     */
     
    FrmGenerarIP GI;
    FrmGenerarMask GM;
    public FrmPrin() {
        initComponents();
        GI=new FrmGenerarIP(this,v1, v2, v3, v4,vb1, vb2, vb3, vb4);
        GM=new FrmGenerarMask(m1, m2, m3, m4,mb1, mb2, mb3, mb4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TIp = new javax.swing.JTabbedPane();
        IpDec = new javax.swing.JPanel();
        v4 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        v3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        IPBin = new javax.swing.JPanel();
        vb2 = new javax.swing.JTextField();
        vb3 = new javax.swing.JTextField();
        vb4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vb1 = new javax.swing.JTextField();
        TMk = new javax.swing.JTabbedPane();
        MkDec = new javax.swing.JPanel();
        m4 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        MkBin = new javax.swing.JPanel();
        mb2 = new javax.swing.JTextField();
        mb3 = new javax.swing.JTextField();
        mb4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mb1 = new javax.swing.JTextField();
        BLimpiar = new javax.swing.JButton();
        BOk = new javax.swing.JButton();
        BGenerar = new javax.swing.JButton();
        BGenerarM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        IpDec.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                IpDecComponentShown(evt);
            }
        });

        v4.setName("3"); // NOI18N

        v2.setName("1"); // NOI18N

        v3.setName("2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setText(".");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel4.setText(".");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel8.setText(".");

        javax.swing.GroupLayout IpDecLayout = new javax.swing.GroupLayout(IpDec);
        IpDec.setLayout(IpDecLayout);
        IpDecLayout.setHorizontalGroup(
            IpDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IpDecLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        IpDecLayout.setVerticalGroup(
            IpDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IpDecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IpDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        v4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionDec(evt);
            }
        });
        v4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ipField.check(evt);
            }
        });
        v2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionDec(evt);
            }
        });
        v2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ipField.check(evt);
            }
        });
        v3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionDec(evt);
            }
        });
        v3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ipField.check(evt);
            }
        });
        v1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionDec(evt);
            }
        });

        v1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ipField.check(evt);
                ipField.GuardarDec(v1, v2, v3, v4);
                ipField.setMask(v1, m1, m2, m3, m4, mb1, mb2, mb3, mb4, TMk,BGenerarM);
            }
        });

        TIp.addTab("IP Decimal", IpDec);

        IPBin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                IPBinComponentShown(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel5.setText(".");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel6.setText(".");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel7.setText(".");

        javax.swing.GroupLayout IPBinLayout = new javax.swing.GroupLayout(IPBin);
        IPBin.setLayout(IPBinLayout);
        IPBinLayout.setHorizontalGroup(
            IPBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IPBinLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(vb1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(vb2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(vb3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(vb4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        IPBinLayout.setVerticalGroup(
            IPBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IPBinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IPBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(vb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(vb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionBin(evt);
            }

        });
        vb3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionBin(evt);
            }
        });
        vb4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionBin(evt);
            }

        });
        vb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipField.RestricionBin(evt);
            }

        });
        vb1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ipField.GuardarBin(vb1, vb2, vb3, vb4);
                ipField.setMask(vb1, m1, m2, m3, m4, mb1, mb2, mb3, mb4, TMk,BGenerarM);
            }
        });

        TIp.addTab("IP Binario", IPBin);

        TMk.setEnabled(false);

        MkDec.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MkDecComponentShown(evt);
            }
        });

        m4.setEditable(false);
        m4.setName("3"); // NOI18N

        m2.setEditable(false);
        m2.setName("1"); // NOI18N

        m3.setEditable(false);
        m3.setName("2"); // NOI18N

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel9.setText(".");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel10.setText(".");

        m1.setEditable(false);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel11.setText(".");

        javax.swing.GroupLayout MkDecLayout = new javax.swing.GroupLayout(MkDec);
        MkDec.setLayout(MkDecLayout);
        MkDecLayout.setHorizontalGroup(
            MkDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MkDecLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        MkDecLayout.setVerticalGroup(
            MkDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MkDecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MkDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        m4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionDec(evt);
            }
        });
        m4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maskField.check(evt);
            }
        });
        m2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionDec(evt);
            }
        });
        m2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maskField.check(evt);
            }
        });
        m3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionDec(evt);
            }
        });
        m3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maskField.check(evt);
            }
        });
        m1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionDec(evt);
            }
        });

        m1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maskField.check(evt);
            }
        });

        TMk.addTab("Máscara Decimal", MkDec);

        MkBin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MkBinComponentShown(evt);
            }
        });

        mb2.setEditable(false);

        mb3.setEditable(false);

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel12.setText(".");

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel13.setText(".");

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel14.setText(".");

        mb1.setEditable(false);

        javax.swing.GroupLayout MkBinLayout = new javax.swing.GroupLayout(MkBin);
        MkBin.setLayout(MkBinLayout);
        MkBinLayout.setHorizontalGroup(
            MkBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MkBinLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(mb1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(0, 0, 0)
                .addComponent(mb2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(mb3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(0, 0, 0)
                .addComponent(mb4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MkBinLayout.setVerticalGroup(
            MkBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MkBinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MkBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(mb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(mb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mb2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionBin(evt);
            }

        });
        mb3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionBin(evt);
            }
        });
        mb4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionBin(evt);
            }

        });
        mb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                maskField.RestricionBin(evt);
            }

        });

        TMk.addTab("Máscara Binario", MkBin);

        BLimpiar.setText("Limpiar");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        BOk.setText("OK");
        BOk.setToolTipText("");
        BOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOkActionPerformed(evt);
            }
        });

        BGenerar.setText("Generar Ip");
        BGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGenerarActionPerformed(evt);
            }
        });

        BGenerarM.setText("Generar Máscara");
        BGenerarM.setEnabled(false);
        BGenerarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGenerarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BGenerarM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BGenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TIp, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TMk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BLimpiar)
                    .addComponent(BOk)
                    .addComponent(BGenerar)
                    .addComponent(BGenerarM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void IpDecComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_IpDecComponentShown
        // TODO add your handling code here:
        ipField.GuardarBin(vb1, vb2, vb3, vb4);
        ipField.abrirDec(v1, v2, v3, v4);
    }//GEN-LAST:event_IpDecComponentShown

    public void setMask(){
        ipField.setMask(v1, m1, m2, m3, m4, mb1, mb2, mb3, mb4, TMk,BGenerarM);
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ipField.Reset();
        maskField.Reset();
    }//GEN-LAST:event_formComponentShown

    private void IPBinComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_IPBinComponentShown
        // TODO add your handling code here:
        ipField.GuardarDec(v1, v2, v3, v4);
        ipField.abrirBin(vb1, vb2, vb3, vb4);
    }//GEN-LAST:event_IPBinComponentShown

    private void MkDecComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MkDecComponentShown
        // TODO add your handling code here:
        maskField.GuardarBin(mb1, mb2, mb3, mb4);
        maskField.abrirDec(m1, m2, m3, m4);
    }//GEN-LAST:event_MkDecComponentShown

    private void MkBinComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MkBinComponentShown
        // TODO add your handling code here:
        maskField.GuardarDec(m1, m2, m3, m4);
        maskField.abrirBin(mb1, mb2, mb3, mb4);
    }//GEN-LAST:event_MkBinComponentShown

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        // TODO add your handling code here:
        ipField.Reset();
        maskField.Reset();
        ipField.abrirBin(vb1, vb2, vb3, vb4);
        ipField.abrirDec(v1, v2, v3, v4);
        maskField.abrirBin(mb1, mb2, mb3, mb4);
        maskField.abrirDec(m1, m2, m3, m4);
        m2.setEditable(false);
        m3.setEditable(false);
        m4.setEditable(false);
        mb2.setEditable(false);
        mb3.setEditable(false);
        mb4.setEditable(false);
        TMk.enable(false);
        BGenerarM.setEnabled(false);
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void BOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOkActionPerformed
        // TODO add your handling code here:
        if(TIp.getSelectedIndex()==0){
            ipField.GuardarDec(v1, v2, v3, v4);
        }
        else{
            ipField.GuardarBin(vb1, vb2, vb3, vb4);
        }
        if(TMk.getSelectedIndex()==0){
            maskField.GuardarDec(m1, m2, m3, m4);
        }
        else{
            maskField.GuardarBin(mb1, mb2, mb3, mb4);
        }
        for(int i=0;i<4;i++){
            if(ipField.ip[i]==-1){
                ipField.ip[i]=0;
            }
            if(maskField.mask[i]==-1){
                maskField.mask[i]=0;
            }
        }
        
        ipField.abrirBin(vb1, vb2, vb3, vb4);
        ipField.abrirDec(v1, v2, v3, v4);
        maskField.abrirBin(mb1, mb2, mb3, mb4);
        maskField.abrirDec(m1, m2, m3, m4);
        if(ipField.ip[0]<=223){
            if(maskField.isOK()){
                FrmInfo info=new FrmInfo();
                info.setLocationRelativeTo(null);
                info.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Escribió una máscara no válida. "
                                                  + "La máscara tiene que ser contigua. "
                                                  + "Escriba una máscara válida.", 
                                                    "Máscara incorrecta", 0);
            }
        }
        else{
            //info.setVisible(true);
             FrmInfo info=new FrmInfo();
             info.setLocationRelativeTo(null);
             info.setVisible(true);
        }
       //new FrmInfo().setVisible(true);
    }//GEN-LAST:event_BOkActionPerformed

    private void BGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGenerarActionPerformed
        // TODO add your handling code here:
        GI.setLocationRelativeTo(this);
        GI.setVisible(true);
    }//GEN-LAST:event_BGenerarActionPerformed

    private void BGenerarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGenerarMActionPerformed
        // TODO add your handling code here:
        if(TIp.getSelectedIndex()==0){
            ipField.GuardarDec(v1, v2, v3, v4);
        }
        else{
            ipField.GuardarBin(vb1, vb2, vb3, vb4);
        }
        if(TMk.getSelectedIndex()==0){
            maskField.GuardarDec(m1, m2, m3, m4);
        }
        else{
            maskField.GuardarBin(mb1, mb2, mb3, mb4);
        }
        
        GM.setLocationRelativeTo(this);
        GM.setVisible(true);
    }//GEN-LAST:event_BGenerarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGenerar;
    private javax.swing.JButton BGenerarM;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JButton BOk;
    private javax.swing.JPanel IPBin;
    private javax.swing.JPanel IpDec;
    private javax.swing.JPanel MkBin;
    private javax.swing.JPanel MkDec;
    private javax.swing.JTabbedPane TIp;
    private javax.swing.JTabbedPane TMk;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField mb1;
    private javax.swing.JTextField mb2;
    private javax.swing.JTextField mb3;
    private javax.swing.JTextField mb4;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v3;
    private javax.swing.JTextField v4;
    private javax.swing.JTextField vb1;
    private javax.swing.JTextField vb2;
    private javax.swing.JTextField vb3;
    private javax.swing.JTextField vb4;
    // End of variables declaration//GEN-END:variables
}
