/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ip;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class frmSubNet extends javax.swing.JFrame {

    /**
     * Creates new form frmSubNet
     */
    
    int [] vec1;
    DefaultListModel x;
    int ult;
    public frmSubNet(DefaultListModel x,int [] vec1) {
        initComponents();
        this.x=x;
        SubNet.setModel(x);
        ult=-1;
        this.vec1=vec1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SubNet = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sub Redes");

        SubNet.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        SubNet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubNetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SubNet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubNetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubNetMouseClicked
        // TODO add your handling code here:
        String ip = (String) x.elementAt(SubNet.getSelectedIndex());
        if(ult==SubNet.getSelectedIndex()){
            int p=0;
            String []vip=new String[4];
            vip[0]="";
            vip[1]="";
            vip[2]="";
            vip[3]="";
            for(int i=0;i<ip.length();i++){
                if(ip.charAt(i)=='.'){
                    p++;
                }else{
                    vip[p]+=ip.charAt(i);
                }
            }
            int [] t=new int[4];
            t[0]=Integer.valueOf(vip[0]);
            t[1]=Integer.valueOf(vip[1]);
            t[2]=Integer.valueOf(vip[2]);
            t[3]=Integer.valueOf(vip[3]);
            
            ipField.ip=t.clone();
            maskField.mask=vec1.clone();
            
            FrmInfo obj=new FrmInfo();
            obj.setLocationRelativeTo(this);
            obj.setVisible(true);
        }
        else{
            ult=SubNet.getSelectedIndex();
        }
    }//GEN-LAST:event_SubNetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSubNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSubNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSubNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSubNet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmSubNet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList SubNet;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
